name: build and install action
description: A reusable set of build and install steps for pg_lake
inputs:
  pg_version:
    description: 'PostgreSQL version'
    required: true
  container_os:
    description: 'Container OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Export PGDIR, PATH and PG_REGRESS_DIR
      shell: bash
      run: |
        echo "PGDIR=/home/postgres/pgsql-${{ inputs.pg_version }}" >> $GITHUB_ENV
        echo "PG_LIBDIR=/home/postgres/pgsql-${{ inputs.pg_version }}/lib" >> $GITHUB_ENV
        echo "PG_INCLUDEDIR=/home/postgres/pgsql-${{ inputs.pg_version }}/include" >> $GITHUB_ENV
        echo "PATH=/home/postgres/pgsql-${{ inputs.pg_version }}/bin:$PATH" >> $GITHUB_ENV
        echo "PG_REGRESS_DIR=/home/postgres/pgsql-${{ inputs.pg_version }}/regress" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: cache_pipenv
      name: Cache pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: pipenv-${{ inputs.container_os }}-${{ hashFiles('Pipfile.lock') }}

    - name: Install pipenv dependencies
      if: steps.cache_pipenv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python3.11 -m pipenv install --dev

    - name: Check for typos # ;)
      uses: ./.github/actions/check-typos

    - uses: actions/cache@v4
      id: cache_libduckdb
      name: Cache libduckdb
      with:
        key: duckdb_pglake-${{ inputs.container_os }}-${{ hashFiles('duckdb_pglake/src/**', 'duckdb_pglake/Makefile', 'duckdb_pglake/patches/**', 'duckdb_pglake/extension_config.cmake', 'duckdb_pglake/CMakeLists.txt') }}
        path: |
          ${{ env.PG_LIBDIR }}/libduckdb.so
          ${{ env.PG_INCLUDEDIR }}/duckdb
          ${{ env.PG_INCLUDEDIR }}/duckdb.h
          ${{ env.PG_INCLUDEDIR }}/duckdb.hpp
          ${{ env.PG_INCLUDEDIR }}/duckdb_extension.h

    - uses: actions/cache@v4
      id: cache_polaris
      name: Cache Polaris
      with:
        key: polaris-${{ inputs.container_os }}-${{ hashFiles('test_common/rest_catalog/Makefile') }}
        path: |
          /home/postgres/pgsql-${{ inputs.pg_version }}/bin/polaris-admin.jar
          /home/postgres/pgsql-${{ inputs.pg_version }}/bin/polaris-server.jar

    - name: Compile and install all extensions and pgduck_server
      shell: bash
      run: |
        export PGCOMPAT_BUILD_CONFIG=Release

        if [ -f "${{ env.PG_LIBDIR }}/libduckdb.so" -a -f "${{ env.PG_INCLUDEDIR }}/duckdb.h" ]; then
          export DUCKDB_BUILD_USE_CACHE=1;
        else
          export DUCKDB_BUILD_USE_CACHE=0;
        fi

        make install-pgduck_server && make install-pg_lake_spatial && make install-pg_lake_benchmark

    - name: Build Polaris if not already in the cache
      if: steps.cache_polaris.outputs.cache-hit != 'true'
      shell: bash
      run: |
        make -j16 install-rest_catalog

    - name: Install the test extensions
      shell: bash
      run: |
        make -C pg_extension_base prepare-check
        make -C pg_lake_table prepare-check

    - name: Upload postgres-${{ inputs.pg_version }} artifacts for ${{ inputs.container_os }}
      uses: actions/upload-artifact@v4
      with:
        name: postgres-${{ inputs.pg_version }}-${{ inputs.container_os }}-artifacts
        path: /home/postgres/pgsql-${{ inputs.pg_version }}/

    # need to upload once, same for all pg versions
    - name: Upload avro artifacts for ${{ inputs.container_os }}
      if: ${{ inputs.pg_version == 18 }}
      uses: actions/upload-artifact@v4
      with:
        name: avro-${{ inputs.container_os }}-artifacts
        path: ./avro/lang/c/build/avrolib
