-- Upgrade script for pg_lake_table from 3.3 to 3.4
--
-- The DuckLake access method, foreign-data wrapper, server, and validator
-- definitions previously lived here; they moved into pg_lake_ducklake--3.4.sql
-- so pg_lake_table no longer depends on the pg_lake_ducklake extension.
